---
name: Data-Typed-Expression
version: 0.001
author:
  - 'Przemyslaw Wesolek <jest@go.art.pl>'
abstract: Parsing typed expressions
license: artistic_2
build_requires:
  Test::Exception: 0.21
  Test::More: 0
requires:
  Carp: 0
  Text::Balanced: 0
configure_requires:
  Module::Build: 0.35
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  Data::Typed::Expression:
    file: lib/Data/Typed/Expression.pm
    version: 0.001
  Data::Typed::Expression::Env:
    file: lib/Data/Typed/Expression/Env.pm
    version: 0.001
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
